# Generated by Django 3.2.18 on 2023-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_trans', '0002_alter_images_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='id',
        ),
        migrations.AddField(
            model_name='images',
            name='unique_key',
            field=models.AutoField(default=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
